version: '3.7'

services:
  celery:
    build:
      context: ./app
    env_file:
      - ./.env.prod
    command: celery -A django_app worker -l INFO
    volumes:
      - ./app/:/usr/src/app
    depends_on:
      - redis
      - db
  # web:
  #   build:
  #     context: ./app
  #     dockerfile: Dockerfile.prod
  #   command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
  #   ports:
  #     - 8000:8000
  #   env_file:
  #     - ./.env.prod
  #   depends_on:
  #     - db
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: "redis:alpine"

    command: redis-server 

    ports:
     - "6379:6379"

    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/src/app/redis.conf

    environment:
     - REDIS_REPLICATION_MODE=master

    networks:
      node_net:
        ipv4_address: 172.28.1.4

# networking for the Redis container
networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16


volumes:
  postgres_data: