# Generated by Django 3.0.7 on 2020-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ODE_finder', '0004_auto_20201012_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationresult',
            name='signal_preprocessor',
            field=models.CharField(choices=[('GP', 'Gaussian Process'), ('SP', 'Spline'), ('NA', 'None')], default='SP', max_length=2),
        ),
    ]
